import { FortuneTigerItemType } from "./EnumType";
import Tool from "./Tool";
import { IncanWondersItem, NormalSpinItem } from "./Type";


class CreateSpinData {


    static initArray(rl: number[], value: number) {
        for (let i = 0; i < rl.length; i++) {
            rl[i] = value
        }
        return rl
    }



    static createFortuneTigerData() {
        let sourceData: NormalSpinItem[] = [{
            "dt": {
                "si": {
                    "wc": 0,
                    "ist": false,
                    "itw": false,
                    "fws": 3,
                    "wp": {
                        "1": [
                            1,
                            4,
                            7
                        ],
                        "2": [
                            0,
                            3,
                            6
                        ],
                        "3": [
                            2,
                            5,
                            8
                        ],
                        "4": [
                            0,
                            4,
                            8
                        ],
                        "5": [
                            2,
                            4,
                            6
                        ]
                    },
                    "orl": [
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3
                    ],
                    "lw": {
                        "1": 2,
                        "2": 2,
                        "3": 2,
                        "4": 2,
                        "5": 2
                    },
                    "irs": false,
                    "gwt": 4,
                    "fb": null,
                    "ctw": 100,
                    "pmt": null,
                    "cwc": 1,
                    "fstc": null,
                    "pcwc": 1,
                    "rwsp": {
                        "1": 25,
                        "2": 25,
                        "3": 25,
                        "4": 25,
                        "5": 25
                    },
                    "hashr": "0:3;3;3#3;3;3#3;3;3#R#3#011121#MV#0.15#MT#1#R#3#001020#MV#0.15#MT#1#R#3#021222#MV#0.15#MT#1#R#3#001122#MV#0.15#MT#1#R#3#021120#MV#0.15#MT#1#MG#37.50#",
                    "ml": 1,
                    "cs": 0.08,
                    "rl": [
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3
                    ],
                    "sid": "17654963506117736",
                    "psid": "17654963506117736",
                    "st": 1,
                    "nst": 1,
                    "pf": 2,
                    "aw": 100,
                    "wid": 0,
                    "wt": "C",
                    "wk": "0_C",
                    "wbn": null,
                    "wfg": null,
                    "blb": 200,
                    "blab": 199.6,
                    "bl": 299.6,
                    "tb": 0.4,
                    "tbb": 0.4,
                    "tw": 100,
                    "np": 99.6,
                    "ocr": null,
                    "mr": null,
                    "ge": [
                        1,
                        11
                    ]
                }
            },
            "err": null
        }] as unknown as NormalSpinItem[]




        let initYuRuYiOne = () => {
            let results = []
            for (let i = 0; i < 9; i++) {
                let newData: NormalSpinItem[] = Tool.deepClone(sourceData)
                let rl = newData[0].dt.si.rl
                CreateSpinData.initArray(rl, FortuneTigerItemType.YuRuYi)
                rl[i] = FortuneTigerItemType.Wild
                newData[0].dt.si.orl = newData[0].dt.si.rl
                results.push(newData)
            }
            return results
        }

        let initYuRuYiTwo = () => {
            let results = []
            for (let i = 0; i < 9; i++) {
                for (let j = i + 1; j < 9; j++) {
                    let newData: NormalSpinItem[] = Tool.deepClone(sourceData)
                    let rl = newData[0].dt.si.rl
                    CreateSpinData.initArray(rl, FortuneTigerItemType.YuRuYi)
                    rl[i] = FortuneTigerItemType.Wild
                    rl[j] = FortuneTigerItemType.Wild
                    newData[0].dt.si.orl = newData[0].dt.si.rl
                    results.push(newData)
                }
            }

            return results
        }

        let initYuRuYiThree = () => {
            let results = []
            for (let i = 0; i < 9; i++) {
                for (let j = i + 1; j < 9; j++) {
                    for (let k = j + 1; k < 9; k++) {
                        let newData: NormalSpinItem[] = Tool.deepClone(sourceData)
                        let rl = newData[0].dt.si.rl
                        CreateSpinData.initArray(rl, FortuneTigerItemType.YuRuYi)
                        rl[i] = FortuneTigerItemType.Wild
                        rl[j] = FortuneTigerItemType.Wild
                        rl[k] = FortuneTigerItemType.Wild
                        newData[0].dt.si.orl = newData[0].dt.si.rl
                        results.push(newData)
                    }
                }
            }

            return results
        }

        let sourceMap = new Map<string, string>()


        let result1 = initYuRuYiOne()
        let result2 = initYuRuYiTwo()
        let result3 = initYuRuYiThree()
        let results: NormalSpinItem[][] = [...result1, ...result2, ...result3]

        for (let i = 0; i < results.length; i++) {
            let newData = results[i]
            newData[0].dt.si.sid = "17654963506117736" + i
            newData[0].dt.si.psid = "17654963506117736" + i
            newData[0].dt.si.hashr = "0:3;3;3#3;3;3#3;3;3#R#3#011121#MV#0.15#MT#1#R#3#001020#MV#0.15#MT#1#R#3#021222#MV#0.15#MT#1#R#3#001122#MV#0.15#MT#1#R#3#021120#MV#0.15#MT#1#MG#37.50#" + i


            let stringData = JSON.stringify(newData.map((o) => JSON.stringify(o)));
            let fileName = Tool.makeDeterministicName(stringData)
            if (sourceMap.get(fileName)) {

                continue
            }
            sourceMap.set(fileName, stringData)
        }

        console.log(results)

        console.log(`一共造出${sourceMap.size}条数据`)
        for (let [fileName, stringData] of sourceMap) {
            Tool.writeFile(`gen_tiger_data/${fileName}`, stringData)
            //console.log(`gen file${fileName}`)
        }

    }


    static createGraffitiRush() {
        let data1 = {
            dt: {
                si: {
                    pf: 1,
                    aw: 16.2,
                    wid: 0,
                    wk: "0_C",
                    esp: null,
                    ssaw: 16.2,
                    fs: null,
                    gwt: 2,
                    cwc: 1,
                    tb: 0.4,
                    tw: 16.2,
                    ml: 1,
                    crtw: 0,
                    orl: [
                        2,
                        2,
                        2,
                        2,
                        4,
                        6,
                        8,
                        9,
                        0,
                        0,
                        0,
                        8,
                        0,
                        2,
                        2,
                        0,
                    ],
                    imw: false,
                    hashr: "0:9;4;0;0#9;6;0;2#9;8;0;2#9;9;8;0#R#9#00010203#MV#0.2#MT#1#R#8#20212223#MV#0.2#MT#1#R#2#30313233#MV#0.2#MT#1#MG#3.3#",
                    np: 15.8,
                    ge: [
                        1,
                        11,
                    ],
                    lw: {
                        "5": 8,
                        "7": 0.2,
                        "8": 8,
                    },
                    gm: 1,
                    fstc: null,
                    rwsp: {
                        "5": 200,
                        "7": 5,
                        "8": 200,
                    },
                    rl: [
                        2,
                        2,
                        2,
                        2,
                        4,
                        6,
                        8,
                        9,
                        0,
                        0,
                        0,
                        8,
                        0,
                        2,
                        2,
                        0,
                    ],
                    bl: 101383.24,
                    efsic: 0,
                    cs: 0.04,
                    st: 1,
                    wfg: null,
                    tbb: 0.4,
                    mr: null,
                    nsp: null,
                    sid: "6801d4bb6a3854af5b35e8ef_1_1",
                    psid: "6801d4bb6a3854af5b35e8ef",
                    ocr: null,
                    wp: {
                        "5": [
                            0,
                            1,
                            2,
                            3,
                        ],
                        "7": [
                            8,
                            9,
                            10,
                            11,
                        ],
                        "8": [
                            12,
                            13,
                            14,
                            15,
                        ],
                    },
                    sc: 0,
                    pcwc: 1,
                    fb: null,
                    blab: 101374.96,
                    lwam: {
                        "5": 8,
                        "7": 0.2,
                        "8": 8,
                    },
                    iesf: false,
                    pmt: null,
                    wt: "C",
                    wbn: null,
                    blb: 101375.36,
                    sp: null,
                    ctw: 16.2,
                    ab: null,
                    nst: 1,
                },
            },
            err: null,
        }//40.5

        let data2 = {
            dt: {
                si: {
                    pf: 1,
                    aw: 18,
                    wid: 0,
                    wk: "0_C",
                    esp: null,
                    ssaw: 18,
                    fs: null,
                    gwt: 2,
                    cwc: 1,
                    tb: 0.4,
                    tw: 18,
                    ml: 1,
                    crtw: 0,
                    orl: [
                        2,
                        2,
                        2,
                        2,
                        4,
                        6,
                        8,
                        9,
                        4,
                        4,
                        4,
                        4,
                        0,
                        2,
                        2,
                        0,
                    ],
                    imw: false,
                    hashr: "0:9;4;0;0#9;6;0;2#9;8;0;2#9;9;8;0#R#9#00010203#MV#0.2#MT#1#R#8#20212223#MV#0.2#MT#1#R#2#30313233#MV#0.2#MT#1#MG#3.3#",
                    np: 17.6,
                    ge: [
                        1,
                        11,
                    ],
                    lw: {
                        "5": 8,
                        "7": 2,
                        "8": 8,
                    },
                    gm: 1,
                    fstc: null,
                    rwsp: {
                        "5": 200,
                        "7": 50,
                        "8": 200,
                    },
                    rl: [
                        2,
                        2,
                        2,
                        2,
                        4,
                        6,
                        8,
                        9,
                        4,
                        4,
                        4,
                        4,
                        0,
                        2,
                        2,
                        0,
                    ],
                    bl: 101383.24,
                    efsic: 0,
                    cs: 0.04,
                    st: 1,
                    wfg: null,
                    tbb: 0.4,
                    mr: null,
                    nsp: null,
                    sid: "6801d4bb6a3854af5b35e8ef_1_1",
                    psid: "6801d4bb6a3854af5b35e8ef",
                    ocr: null,
                    wp: {
                        "5": [
                            0,
                            1,
                            2,
                            3,
                        ],
                        "7": [
                            8,
                            9,
                            10,
                            11,
                        ],
                        "8": [
                            12,
                            13,
                            14,
                            15,
                        ],
                    },
                    sc: 0,
                    pcwc: 1,
                    fb: null,
                    blab: 101374.96,
                    lwam: {
                        "5": 8,
                        "7": 2,
                        "8": 8,
                    },
                    iesf: false,
                    pmt: null,
                    wt: "C",
                    wbn: null,
                    blb: 101375.36,
                    sp: null,
                    ctw: 18,
                    ab: null,
                    nst: 1,
                },
            },
            err: null,
        }//45

        let data3 = {
            dt: {
                si: {
                    pf: 1,
                    aw: 12,
                    wid: 0,
                    wk: "0_C",
                    esp: null,
                    ssaw: 12,
                    fs: null,
                    gwt: 2,
                    cwc: 1,
                    tb: 0.4,
                    tw: 12,
                    ml: 1,
                    crtw: 0,
                    orl: [
                        3,
                        3,
                        3,
                        3,
                        4,
                        6,
                        8,
                        9,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                    ],
                    imw: false,
                    hashr: "0:9;4;0;0#9;6;0;2#9;8;0;2#9;9;8;0#R#9#00010203#MV#0.2#MT#1#R#8#20212223#MV#0.2#MT#1#R#2#30313233#MV#0.2#MT#1#MG#3.3#",
                    np: 11.6,
                    ge: [
                        1,
                        11,
                    ],
                    lw: {
                        "5": 4,
                        "7": 4,
                        "8": 4,
                    },
                    gm: 1,
                    fstc: null,
                    rwsp: {
                        "5": 100,
                        "7": 100,
                        "8": 100,
                    },
                    rl: [
                        3,
                        3,
                        3,
                        3,
                        4,
                        6,
                        8,
                        9,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                        3,
                    ],
                    bl: 101383.24,
                    efsic: 0,
                    cs: 0.04,
                    st: 1,
                    wfg: null,
                    tbb: 0.4,
                    mr: null,
                    nsp: null,
                    sid: "6801d4bb6a3854af5b35e8ef_1_1",
                    psid: "6801d4bb6a3854af5b35e8ef",
                    ocr: null,
                    wp: {
                        "5": [
                            0,
                            1,
                            2,
                            3,
                        ],
                        "7": [
                            8,
                            9,
                            10,
                            11,
                        ],
                        "8": [
                            12,
                            13,
                            14,
                            15,
                        ],
                    },
                    sc: 0,
                    pcwc: 1,
                    fb: null,
                    blab: 101374.96,
                    lwam: {
                        "5": 4,
                        "7": 4,
                        "8": 4,
                    },
                    iesf: false,
                    pmt: null,
                    wt: "C",
                    wbn: null,
                    blb: 101375.36,
                    sp: null,
                    ctw: 12,
                    ab: null,
                    nst: 1,
                },
            },
            err: null,
        }//30

        let data4 = {
            dt: {
                si: {
                    ocr: null,
                    lwam: {
                        "2": 8,
                        "6": 2,
                    },
                    crtw: 0,
                    iesf: false,
                    fs: null,
                    ctw: 10,
                    fb: null,
                    wid: 0,
                    wbn: null,
                    lw: {
                        "2": 8,
                        "6": 2,
                    },
                    sc: 0,
                    gwt: 2,
                    rwsp: {
                        "2": 200,
                        "6": 50,
                    },
                    nst: 1,
                    pf: 1,
                    wfg: null,
                    np: 9.6,
                    nsp: null,
                    pmt: null,
                    blab: 100403,
                    tw: 10,
                    efsic: 0,
                    ab: null,
                    cs: 0.04,
                    wt: "C",
                    tbb: 0.4,
                    mr: null,
                    ml: 1,
                    wp: {
                        "2": [
                            1,
                            5,
                            9,
                            13,
                        ],
                        "6": [
                            4,
                            5,
                            6,
                            7,
                        ],
                    },
                    sp: null,
                    fstc: null,
                    aw: 10,
                    wk: "0_C",
                    blb: 100403.4,
                    ssaw: 10,
                    cwc: 1,
                    hashr: "0:9;0;8;8#2;0;2;0#7;9;9;8#3;9;7;5#R#2#01112131#MV#0.2#MT#1#R#9#10111213#MV#0.2#MT#1#MG#3.2#",
                    sid: "6802f6591b16cbc1a1a38c35_1_1",
                    psid: "6802f6591b16cbc1a1a38c35",
                    st: 1,
                    ge: [
                        1,
                        11,
                    ],
                    orl: [
                        9,
                        2,
                        7,
                        3,
                        0,
                        0,
                        4,
                        4,
                        8,
                        2,
                        9,
                        7,
                        8,
                        0,
                        8,
                        5,
                    ],
                    imw: false,
                    gm: 1,
                    esp: null,
                    pcwc: 1,
                    rl: [
                        9,
                        2,
                        7,
                        3,
                        0,
                        0,
                        4,
                        4,
                        8,
                        2,
                        9,
                        7,
                        8,
                        0,
                        8,
                        5,
                    ],
                    bl: 100411.08,
                    tb: 0.4,
                },
            },
            err: null,
        }//25

        let arr = [data1, data2, data3, data4]
        let fileName = "aaaaaaaaa_"
        for (let i = 0; i < arr.length; i++) {
            arr[i].dt.si.hashr = arr[i].dt.si.hashr + `_${i}`
            arr[i].dt.si.sid = arr[i].dt.si.sid + `_${i}`
            arr[i].dt.si.psid = arr[i].dt.si.psid + `_${i}`
            let newData = [arr[i]]
            let stringData = JSON.stringify(newData.map((o) => JSON.stringify(o)));
            Tool.writeFile(`gen_graffitirush_data/${fileName}_${i}.json`, stringData)
        }
    }

    static createIncanWonders() {

        let win_bet_9 = [
            {
                dt: {
                    si: {
                        imw: false,
                        cwc: 0,
                        hashr: "0:6;3;6#6;3;6#6;3;6#MV#0.1#MT#1#MG#0.0#",
                        ml: 1,
                        cs: 0.08,
                        blb: 100021.04,
                        tb: 0.4,
                        tw: 0,
                        lw: null,
                        gm: 1,
                        orl: [
                            6,
                            6,
                            6,
                            3,
                            3,
                            3,
                            6,
                            6,
                            6,
                        ],
                        ssaw: 0,
                        rcl: 1,
                        pcwc: 0,
                        ab: null,
                        rl: [
                            6,
                            6,
                            6,
                            3,
                            3,
                            3,
                            6,
                            6,
                            6,
                        ],
                        ibs: false,
                        ctw: 0,
                        fstc: null,
                        aw: 0,
                        tbb: 0.4,
                        isf: true,
                        ism: false,
                        bl: 100020.64,
                        ge: [
                            2,
                            11,
                        ],
                        wp: null,
                        it: false,
                        smr: null,
                        crtw: 0,
                        bns: null,
                        pmt: null,
                        sid: "68080b375d58a3ccf7c1515c_1_11",
                        st: 1,
                        fb: null,
                        psid: "68080b375d58a3ccf7c1515c",
                        nst: 4,
                        wt: "C",
                        blab: 100020.64,
                        mr: null,
                        gwt: -1,
                        pf: 1,
                        wid: 0,
                        wk: "0_C",
                        wbn: null,
                        wfg: null,
                        ocr: null,
                        rwsp: null,
                        np: -0.4,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        st: 4,
                        wbn: null,
                        ab: null,
                        wk: "0_C",
                        tb: 0,
                        tw: 0,
                        np: 0,
                        mr: null,
                        cwc: 0,
                        rwsp: null,
                        ge: [
                            2,
                            11,
                        ],
                        rl: [
                            6,
                            6,
                            6,
                            5,
                            5,
                            5,
                            6,
                            6,
                            6,
                        ],
                        wp: null,
                        gm: 1,
                        orl: [
                            6,
                            6,
                            6,
                            5,
                            5,
                            5,
                            6,
                            6,
                            6,
                        ],
                        ctw: 0,
                        wid: 0,
                        tbb: 0.4,
                        ibs: false,
                        smr: null,
                        psid: "68080b375d58a3ccf7c1515c",
                        pf: 1,
                        wt: "C",
                        ocr: null,
                        lw: null,
                        imw: false,
                        fstc: {
                            "4": 1,
                        },
                        cs: 0.08,
                        wfg: null,
                        blab: 100020.64,
                        bl: 100020.64,
                        it: false,
                        pcwc: 0,
                        blb: 100020.64,
                        sid: "68080b375d58a3ccf7c1515c_2_11",
                        ssaw: 0,
                        crtw: 0,
                        rcl: 1,
                        pmt: null,
                        fb: null,
                        nst: 4,
                        aw: 0,
                        ml: 1,
                        isf: false,
                        ism: false,
                        bns: null,
                        gwt: -1,
                        hashr: "1:6;5;6#6;5;6#6;5;6#MV#0.0#MT#1#MG#0.0#",
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        rwsp: null,
                        fb: null,
                        psid: "68080b375d58a3ccf7c1515c",
                        pf: 1,
                        gm: 1,
                        isf: false,
                        ibs: false,
                        ssaw: 0,
                        aw: 0,
                        tbb: 0.4,
                        ge: [
                            2,
                            11,
                        ],
                        crtw: 0,
                        ab: null,
                        rl: [
                            6,
                            6,
                            6,
                            5,
                            5,
                            3,
                            6,
                            6,
                            6,
                        ],
                        st: 4,
                        wk: "0_C",
                        wbn: null,
                        wfg: null,
                        blab: 100020.64,
                        it: false,
                        ml: 1,
                        cs: 0.08,
                        wid: 0,
                        wt: "C",
                        bl: 100020.64,
                        tb: 0,
                        mr: null,
                        ism: false,
                        imw: false,
                        lw: null,
                        bns: null,
                        blb: 100020.64,
                        np: 0,
                        ocr: null,
                        cwc: 0,
                        tw: 0,
                        orl: [
                            6,
                            6,
                            6,
                            5,
                            5,
                            3,
                            6,
                            6,
                            6,
                        ],
                        smr: null,
                        rcl: 1,
                        gwt: -1,
                        ctw: 0,
                        hashr: "2:6;5;6#6;5;6#6;3;6#MV#0.0#MT#1#MG#0.0#",
                        sid: "68080b375d58a3ccf7c1515c_3_11",
                        nst: 4,
                        wp: null,
                        pmt: null,
                        fstc: {
                            "4": 2,
                        },
                        pcwc: 0,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        isf: false,
                        ibs: false,
                        ml: 1,
                        psid: "68080b375d58a3ccf7c1515c",
                        pf: 1,
                        aw: 0,
                        wfg: null,
                        tbb: 0.4,
                        lw: null,
                        ism: false,
                        ctw: 0,
                        hashr: "3:6;7;6#6;7;6#6;7;6#MV#0.0#MT#1#MG#0.0#",
                        nst: 4,
                        wid: 0,
                        bl: 100020.64,
                        gm: 1,
                        it: false,
                        rcl: 1,
                        cwc: 0,
                        blab: 100020.64,
                        tb: 0,
                        np: 0,
                        imw: false,
                        wt: "C",
                        wk: "0_C",
                        rl: [
                            6,
                            6,
                            6,
                            7,
                            7,
                            7,
                            6,
                            6,
                            6,
                        ],
                        st: 4,
                        wbn: null,
                        ocr: null,
                        mr: null,
                        cs: 0.08,
                        crtw: 0,
                        bns: null,
                        pmt: null,
                        fb: null,
                        blb: 100020.64,
                        wp: null,
                        smr: null,
                        gwt: -1,
                        fstc: {
                            "4": 3,
                        },
                        pcwc: 0,
                        ab: null,
                        sid: "68080b375d58a3ccf7c1515c_4_11",
                        ge: [
                            2,
                            11,
                        ],
                        orl: [
                            6,
                            6,
                            6,
                            7,
                            7,
                            7,
                            6,
                            6,
                            6,
                        ],
                        ssaw: 0,
                        rwsp: null,
                        tw: 0,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        ibs: false,
                        bns: null,
                        rwsp: null,
                        wbn: null,
                        blb: 100020.64,
                        wp: null,
                        crtw: 0,
                        rcl: 1,
                        hashr: "4:6;5;6#6;5;6#6;5;6#MV#0.0#MT#1#MG#0.0#",
                        fb: null,
                        rl: [
                            6,
                            6,
                            6,
                            5,
                            5,
                            5,
                            6,
                            6,
                            6,
                        ],
                        nst: 4,
                        bl: 100020.64,
                        isf: false,
                        imw: false,
                        sid: "68080b375d58a3ccf7c1515c_5_11",
                        mr: null,
                        ge: [
                            2,
                            11,
                        ],
                        gm: 1,
                        orl: [
                            6,
                            6,
                            6,
                            5,
                            5,
                            5,
                            6,
                            6,
                            6,
                        ],
                        ssaw: 0,
                        pf: 1,
                        wk: "0_C",
                        ocr: null,
                        it: false,
                        smr: null,
                        pmt: null,
                        pcwc: 0,
                        ab: null,
                        tb: 0,
                        fstc: {
                            "4": 4,
                        },
                        st: 4,
                        gwt: -1,
                        cwc: 0,
                        cs: 0.08,
                        psid: "68080b375d58a3ccf7c1515c",
                        wid: 0,
                        wt: "C",
                        wfg: null,
                        blab: 100020.64,
                        lw: null,
                        ism: false,
                        ctw: 0,
                        ml: 1,
                        aw: 0,
                        tbb: 0.4,
                        tw: 0,
                        np: 0,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        hashr: "5:6;4;6#6;4;6#6;4;6#MV#0.0#MT#1#MG#0.0#",
                        wfg: null,
                        np: 0,
                        lw: null,
                        ab: null,
                        psid: "68080b375d58a3ccf7c1515c",
                        st: 4,
                        bl: 100020.64,
                        orl: [
                            6,
                            6,
                            6,
                            4,
                            4,
                            4,
                            6,
                            6,
                            6,
                        ],
                        bns: null,
                        cs: 0.08,
                        aw: 0,
                        tw: 0,
                        it: false,
                        ism: false,
                        cwc: 0,
                        sid: "68080b375d58a3ccf7c1515c_6_11",
                        wid: 0,
                        blab: 100020.64,
                        tb: 0,
                        tbb: 0.4,
                        rcl: 1,
                        ctw: 0,
                        pcwc: 0,
                        fb: null,
                        nst: 4,
                        blb: 100020.64,
                        mr: null,
                        ge: [
                            2,
                            11,
                        ],
                        ibs: false,
                        wk: "0_C",
                        isf: false,
                        imw: false,
                        pmt: null,
                        fstc: {
                            "4": 5,
                        },
                        ml: 1,
                        rl: [
                            6,
                            6,
                            6,
                            4,
                            4,
                            4,
                            6,
                            6,
                            6,
                        ],
                        pf: 1,
                        wt: "C",
                        ssaw: 0,
                        crtw: 0,
                        wbn: null,
                        ocr: null,
                        wp: null,
                        gm: 1,
                        smr: null,
                        gwt: -1,
                        rwsp: null,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        blb: 100020.64,
                        ism: false,
                        imw: false,
                        gwt: -1,
                        wid: 0,
                        wt: "C",
                        isf: false,
                        orl: [
                            6,
                            6,
                            6,
                            3,
                            4,
                            4,
                            6,
                            6,
                            6,
                        ],
                        smr: null,
                        rcl: 1,
                        rl: [
                            6,
                            6,
                            6,
                            3,
                            4,
                            4,
                            6,
                            6,
                            6,
                        ],
                        nst: 4,
                        wbn: null,
                        blab: 100020.64,
                        bns: null,
                        ibs: false,
                        ssaw: 0,
                        hashr: "6:6;3;6#6;4;6#6;4;6#MV#0.0#MT#1#MG#0.0#",
                        pf: 1,
                        fstc: {
                            "4": 6,
                        },
                        fb: null,
                        wfg: null,
                        tb: 0,
                        tbb: 0.4,
                        ge: [
                            2,
                            11,
                        ],
                        ab: null,
                        ml: 1,
                        cs: 0.08,
                        sid: "68080b375d58a3ccf7c1515c_7_11",
                        wp: null,
                        gm: 1,
                        it: false,
                        pmt: null,
                        pcwc: 0,
                        psid: "68080b375d58a3ccf7c1515c",
                        aw: 0,
                        bl: 100020.64,
                        tw: 0,
                        np: 0,
                        ocr: null,
                        crtw: 0,
                        ctw: 0,
                        st: 4,
                        mr: null,
                        lw: null,
                        cwc: 0,
                        rwsp: null,
                        wk: "0_C",
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        rl: [
                            6,
                            6,
                            6,
                            2,
                            2,
                            5,
                            6,
                            6,
                            6,
                        ],
                        wid: 0,
                        bl: 100020.64,
                        tw: 0,
                        np: 0,
                        mr: null,
                        gwt: -1,
                        pmt: null,
                        rwsp: null,
                        wk: "0_C",
                        wfg: null,
                        lw: null,
                        ibs: false,
                        ism: false,
                        fstc: {
                            "4": 7,
                        },
                        sid: "68080b375d58a3ccf7c1515c_8_11",
                        psid: "68080b375d58a3ccf7c1515c",
                        nst: 4,
                        blb: 100020.64,
                        ssaw: 0,
                        crtw: 0,
                        imw: false,
                        bns: null,
                        tb: 0,
                        ocr: null,
                        wp: null,
                        gm: 1,
                        it: false,
                        orl: [
                            6,
                            6,
                            6,
                            2,
                            2,
                            5,
                            6,
                            6,
                            6,
                        ],
                        ctw: 0,
                        st: 4,
                        pf: 1,
                        aw: 0,
                        smr: null,
                        cwc: 0,
                        fb: null,
                        cs: 0.08,
                        wt: "C",
                        blab: 100020.64,
                        ge: [
                            2,
                            11,
                        ],
                        isf: false,
                        rcl: 1,
                        pcwc: 0,
                        tbb: 0.4,
                        hashr: "7:6;2;6#6;2;6#6;5;6#MV#0.0#MT#1#MG#0.0#",
                        ab: null,
                        ml: 1,
                        wbn: null,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        aw: 0,
                        blb: 100020.64,
                        tbb: 0.4,
                        np: 0,
                        smr: [
                            7,
                            6,
                            6,
                            6,
                            2,
                        ],
                        gwt: -1,
                        wfg: null,
                        tb: 0,
                        tw: 0,
                        cs: 0.08,
                        ism: true,
                        rcl: 1,
                        ctw: 1.2,
                        pmt: null,
                        pcwc: 0,
                        wbn: null,
                        blab: 100020.64,
                        lw: {
                            "1": 0.24,
                            "2": 0.24,
                            "3": 0.24,
                            "4": 0.24,
                            "5": 0.24,
                        },
                        gm: 1,
                        bns: null,
                        cwc: 0,
                        rl: [
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        bl: 100020.64,
                        mr: null,
                        isf: false,
                        psid: "68080b375d58a3ccf7c1515c",
                        wt: "C",
                        ssaw: 0,
                        ab: null,
                        wk: "0_C",
                        ocr: null,
                        hashr: "8:6;6;6#6;6;6#6;6;6#R#6#011121#MV#0.0#MT#1#R#6#001020#MV#0.0#MT#1#R#6#021222#MV#0.0#MT#1#R#6#001122#MV#0.0#MT#1#R#6#021120#MV#0.0#MT#1#MG#0.0#",
                        sid: "68080b375d58a3ccf7c1515c_9_11",
                        wp: {
                            "1": [
                                1,
                                4,
                                7,
                            ],
                            "2": [
                                0,
                                3,
                                6,
                            ],
                            "3": [
                                2,
                                5,
                                8,
                            ],
                            "4": [
                                0,
                                4,
                                8,
                            ],
                            "5": [
                                2,
                                4,
                                6,
                            ],
                        },
                        crtw: 0,
                        rwsp: {
                            "1": 3,
                            "2": 3,
                            "3": 3,
                            "4": 3,
                            "5": 3,
                        },
                        nst: 3,
                        ge: [
                            3,
                            11,
                        ],
                        ibs: true,
                        orl: [
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        imw: false,
                        fstc: {
                            "4": 8,
                        },
                        fb: null,
                        st: 4,
                        pf: 1,
                        wid: 0,
                        it: false,
                        ml: 1,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        ism: false,
                        imw: false,
                        rl: [
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                        ],
                        sid: "68080b375d58a3ccf7c1515c_10_11",
                        psid: "68080b375d58a3ccf7c1515c",
                        blab: 100020.64,
                        orl: [
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                        ],
                        ssaw: 0,
                        smr: null,
                        fb: null,
                        wk: "0_C",
                        bl: 100020.64,
                        wp: null,
                        isf: false,
                        cs: 0.08,
                        np: 0,
                        ab: null,
                        ibs: true,
                        bns: {
                            mrl: [
                                0,
                                3,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                            ],
                            ltw: 1.2,
                            lws: 6,
                            nmp: 1,
                        },
                        ctw: 0,
                        fstc: {
                            "3": 1,
                            "4": 8,
                        },
                        pcwc: 0,
                        pf: 1,
                        aw: 0,
                        gm: 3,
                        wt: "C",
                        wbn: null,
                        wfg: null,
                        ocr: null,
                        mr: null,
                        ge: [
                            3,
                            11,
                        ],
                        lw: null,
                        cwc: 0,
                        tbb: 0.4,
                        it: false,
                        crtw: 0,
                        pmt: null,
                        rwsp: null,
                        ml: 1,
                        blb: 100020.64,
                        tb: 0,
                        rcl: -1,
                        gwt: -1,
                        hashr: "9:-1;-1;-1#-1;-1;-1#-1;-1;-1#MV#0.0#MT#3#MG#0.0#",
                        st: 3,
                        nst: 3,
                        wid: 0,
                        tw: 0,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        st: 3,
                        wk: "0_C",
                        gm: 3,
                        orl: [
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        hashr: "10:6;6;6#6;6;6#6;6;6#MV#0.0#MT#3#MG#0.5#",
                        rl: [
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        aw: 3.6,
                        blab: 100020.64,
                        mr: null,
                        ge: [
                            1,
                            11,
                        ],
                        it: false,
                        isf: false,
                        pmt: null,
                        tb: 0,
                        np: 3.6,
                        ibs: true,
                        smr: null,
                        rcl: -1,
                        cwc: 2.666667,
                        fstc: {
                            "3": 2,
                            "4": 8,
                        },
                        cs: 0.08,
                        nst: 1,
                        lw: null,
                        bns: {
                            nmp: -1,
                            mrl: [
                                0,
                                3,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                            ],
                            ltw: 1.2,
                            lws: 6,
                        },
                        ctw: 3.6,
                        sid: "68080b375d58a3ccf7c1515c_11_11",
                        psid: "68080b375d58a3ccf7c1515c",
                        tbb: 0.4,
                        crtw: 0,
                        pcwc: 0,
                        fb: null,
                        bl: 100024.24,
                        ocr: null,
                        gwt: 2,
                        ab: null,
                        pf: 1,
                        wid: 0,
                        wt: "C",
                        wfg: null,
                        wp: null,
                        ssaw: 0,
                        wbn: null,
                        blb: 100020.64,
                        tw: 3.6,
                        ism: false,
                        imw: false,
                        rwsp: null,
                        ml: 1,
                    },
                },
                err: null,
            },
        ] as unknown as IncanWondersItem[]

        let win_bet_12 = [
            {
                dt: {
                    si: {
                        cs: 0.08,
                        wbn: null,
                        bl: 100834.16,
                        tw: 0,
                        ab: null,
                        rl: [
                            2,
                            2,
                            7,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        bns: null,
                        lw: null,
                        isf: false,
                        ibs: false,
                        cwc: 0,
                        hashr: "0:2;6;6#2;6;6#7;6;6#MV#0.1#MT#1#MG#0.0#",
                        smr: null,
                        fstc: null,
                        pcwc: 0,
                        sid: "68081e2a5d58a3ccf7c164fa_1_14",
                        st: 1,
                        nst: 4,
                        pf: 1,
                        wt: "C",
                        imw: false,
                        rcl: 0,
                        aw: 0,
                        wk: "0_C",
                        tbb: 0.4,
                        np: -0.4,
                        ssaw: 0,
                        crtw: 0,
                        gwt: -1,
                        ctw: 0,
                        rwsp: null,
                        wfg: null,
                        blb: 100834.56,
                        blab: 100834.16,
                        fb: null,
                        wp: null,
                        orl: [
                            2,
                            2,
                            7,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        ocr: null,
                        it: false,
                        psid: "68081e2a5d58a3ccf7c164fa",
                        mr: null,
                        gm: 1,
                        ml: 1,
                        wid: 0,
                        tb: 0.4,
                        ge: [
                            2,
                            11,
                        ],
                        ism: false,
                        pmt: null,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        lw: null,
                        ssaw: 0,
                        aw: 0,
                        wk: "0_C",
                        mr: null,
                        wp: null,
                        ab: null,
                        ml: 1,
                        pf: 1,
                        ge: [
                            2,
                            11,
                        ],
                        crtw: 0,
                        imw: false,
                        cwc: 0,
                        fstc: {
                            "4": 1,
                        },
                        rwsp: null,
                        wt: "C",
                        wfg: null,
                        tbb: 0.4,
                        orl: [
                            4,
                            4,
                            4,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        rcl: 0,
                        nst: 4,
                        gm: 1,
                        it: false,
                        ibs: false,
                        smr: null,
                        gwt: -1,
                        cs: 0.08,
                        wid: 0,
                        bl: 100834.16,
                        bns: null,
                        ctw: 0,
                        pmt: null,
                        pcwc: 0,
                        fb: null,
                        sid: "68081e2a5d58a3ccf7c164fa_2_14",
                        psid: "68081e2a5d58a3ccf7c164fa",
                        wbn: null,
                        st: 4,
                        blb: 100834.16,
                        blab: 100834.16,
                        tb: 0,
                        tw: 0,
                        ocr: null,
                        isf: false,
                        ism: false,
                        hashr: "1:4;6;6#4;6;6#4;6;6#MV#0.0#MT#1#MG#0.0#",
                        rl: [
                            4,
                            4,
                            4,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        np: 0,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        ge: [
                            2,
                            11,
                        ],
                        ctw: 0,
                        pcwc: 0,
                        aw: 0,
                        blb: 100834.16,
                        lw: null,
                        ssaw: 0,
                        ism: false,
                        cs: 0.08,
                        rl: [
                            2,
                            4,
                            4,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        sid: "68081e2a5d58a3ccf7c164fa_3_14",
                        wbn: null,
                        it: false,
                        fstc: {
                            "4": 2,
                        },
                        hashr: "2:2;6;6#4;6;6#4;6;6#MV#0.0#MT#1#MG#0.0#",
                        wid: 0,
                        wk: "0_C",
                        blab: 100834.16,
                        bl: 100834.16,
                        tw: 0,
                        isf: false,
                        imw: false,
                        rcl: 0,
                        gwt: -1,
                        st: 4,
                        wfg: null,
                        mr: null,
                        pmt: null,
                        cwc: 0,
                        ml: 1,
                        np: 0,
                        gm: 1,
                        smr: null,
                        crtw: 0,
                        bns: null,
                        rwsp: null,
                        psid: "68081e2a5d58a3ccf7c164fa",
                        wp: null,
                        ibs: false,
                        fb: null,
                        ab: null,
                        tb: 0,
                        tbb: 0.4,
                        ocr: null,
                        orl: [
                            2,
                            4,
                            4,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        nst: 4,
                        pf: 1,
                        wt: "C",
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        it: false,
                        imw: false,
                        pcwc: 0,
                        ml: 1,
                        rl: [
                            7,
                            2,
                            2,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        wk: "0_C",
                        blab: 100834.16,
                        tb: 0,
                        isf: false,
                        smr: null,
                        gwt: -1,
                        pmt: null,
                        aw: 0,
                        wt: "C",
                        tbb: 0.4,
                        np: 0,
                        sid: "68081e2a5d58a3ccf7c164fa_4_14",
                        lw: null,
                        rwsp: null,
                        ab: null,
                        psid: "68081e2a5d58a3ccf7c164fa",
                        bl: 100834.16,
                        ocr: null,
                        crtw: 0,
                        fstc: {
                            "4": 3,
                        },
                        hashr: "3:7;6;6#2;6;6#2;6;6#MV#0.0#MT#1#MG#0.0#",
                        st: 4,
                        ctw: 0,
                        fb: null,
                        wfg: null,
                        blb: 100834.16,
                        mr: null,
                        wp: null,
                        gm: 1,
                        ibs: false,
                        ssaw: 0,
                        ism: false,
                        bns: null,
                        nst: 4,
                        pf: 1,
                        rcl: 0,
                        cwc: 0,
                        cs: 0.08,
                        wbn: null,
                        tw: 0,
                        orl: [
                            7,
                            2,
                            2,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        wid: 0,
                        ge: [
                            2,
                            11,
                        ],
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        rcl: 0,
                        ctw: 0,
                        wid: 0,
                        bl: 100834.16,
                        ocr: null,
                        mr: null,
                        ssaw: 0,
                        gwt: -1,
                        cwc: 0,
                        fstc: {
                            "4": 4,
                        },
                        ml: 1,
                        rl: [
                            3,
                            5,
                            5,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        pf: 1,
                        isf: false,
                        imw: false,
                        pmt: null,
                        aw: 0,
                        wk: "0_C",
                        blab: 100834.16,
                        tw: 0,
                        cs: 0.08,
                        blb: 100834.16,
                        bns: null,
                        hashr: "4:3;6;6#5;6;6#5;6;6#MV#0.0#MT#1#MG#0.0#",
                        nst: 4,
                        wp: null,
                        it: false,
                        ibs: false,
                        psid: "68081e2a5d58a3ccf7c164fa",
                        wfg: null,
                        tb: 0,
                        gm: 1,
                        orl: [
                            3,
                            5,
                            5,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        rwsp: null,
                        st: 4,
                        wt: "C",
                        tbb: 0.4,
                        np: 0,
                        ge: [
                            2,
                            11,
                        ],
                        lw: null,
                        ism: false,
                        crtw: 0,
                        pcwc: 0,
                        fb: null,
                        ab: null,
                        sid: "68081e2a5d58a3ccf7c164fa_5_14",
                        wbn: null,
                        smr: null,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        rwsp: null,
                        hashr: "5:2;6;6#2;6;6#2;6;6#MV#0.0#MT#1#MG#0.0#",
                        pf: 1,
                        blab: 100834.16,
                        tbb: 0.4,
                        rcl: 0,
                        ctw: 0,
                        cwc: 0,
                        fstc: {
                            "4": 5,
                        },
                        fb: null,
                        rl: [
                            2,
                            2,
                            2,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        wfg: null,
                        ocr: null,
                        gm: 1,
                        smr: null,
                        imw: false,
                        wp: null,
                        it: false,
                        bns: null,
                        cs: 0.08,
                        aw: 0,
                        wid: 0,
                        bl: 100834.16,
                        mr: null,
                        st: 4,
                        wk: "0_C",
                        wbn: null,
                        orl: [
                            2,
                            2,
                            2,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        ism: false,
                        crtw: 0,
                        gwt: -1,
                        nst: 4,
                        isf: false,
                        sid: "68081e2a5d58a3ccf7c164fa_6_14",
                        wt: "C",
                        blb: 100834.16,
                        tb: 0,
                        tw: 0,
                        np: 0,
                        ge: [
                            2,
                            11,
                        ],
                        lw: null,
                        ssaw: 0,
                        ab: null,
                        ml: 1,
                        psid: "68081e2a5d58a3ccf7c164fa",
                        ibs: false,
                        pmt: null,
                        pcwc: 0,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        tbb: 0.4,
                        np: 0,
                        rcl: 0,
                        ctw: 0,
                        fb: null,
                        aw: 0,
                        tb: 0,
                        tw: 0,
                        gm: 1,
                        pmt: null,
                        pcwc: 0,
                        hashr: "6:7;6;6#7;6;6#7;6;6#MV#0.0#MT#1#MG#0.0#",
                        nst: 4,
                        ssaw: 0,
                        rwsp: null,
                        cs: 0.08,
                        rl: [
                            7,
                            7,
                            7,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        pf: 1,
                        wk: "0_C",
                        bl: 100834.16,
                        mr: null,
                        wp: null,
                        isf: false,
                        crtw: 0,
                        gwt: -1,
                        ab: null,
                        ocr: null,
                        smr: null,
                        wbn: null,
                        wfg: null,
                        blb: 100834.16,
                        it: false,
                        imw: false,
                        bns: null,
                        cwc: 0,
                        fstc: {
                            "4": 6,
                        },
                        sid: "68081e2a5d58a3ccf7c164fa_7_14",
                        orl: [
                            7,
                            7,
                            7,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        ml: 1,
                        psid: "68081e2a5d58a3ccf7c164fa",
                        st: 4,
                        wid: 0,
                        wt: "C",
                        ge: [
                            2,
                            11,
                        ],
                        lw: null,
                        ibs: false,
                        ism: false,
                        blab: 100834.16,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        fstc: {
                            "4": 7,
                        },
                        ocr: null,
                        gm: 1,
                        crtw: 0,
                        cwc: 0,
                        ab: null,
                        aw: 0,
                        wbn: null,
                        bl: 100834.16,
                        tb: 0,
                        ssaw: 0,
                        ism: false,
                        ml: 1,
                        mr: null,
                        wp: null,
                        pcwc: 0,
                        hashr: "7:7;6;6#7;6;6#2;6;6#MV#0.0#MT#1#MG#0.0#",
                        st: 4,
                        pf: 1,
                        wt: "C",
                        blb: 100834.16,
                        blab: 100834.16,
                        ibs: false,
                        smr: null,
                        imw: false,
                        rwsp: null,
                        sid: "68081e2a5d58a3ccf7c164fa_8_14",
                        wk: "0_C",
                        tbb: 0.4,
                        np: 0,
                        bns: null,
                        fb: null,
                        cs: 0.08,
                        wid: 0,
                        wfg: null,
                        tw: 0,
                        orl: [
                            7,
                            7,
                            2,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        gwt: -1,
                        pmt: null,
                        rl: [
                            7,
                            7,
                            2,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        nst: 4,
                        ge: [
                            2,
                            11,
                        ],
                        lw: null,
                        it: false,
                        isf: false,
                        rcl: 0,
                        psid: "68081e2a5d58a3ccf7c164fa",
                        ctw: 0,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        gwt: -1,
                        cs: 0.08,
                        ism: false,
                        crtw: 0,
                        ab: null,
                        pf: 1,
                        wid: 0,
                        wt: "C",
                        wfg: null,
                        tb: 0,
                        wp: null,
                        bns: null,
                        cwc: 0,
                        tbb: 0.4,
                        gm: 1,
                        isf: false,
                        ibs: false,
                        rcl: 0,
                        fstc: {
                            "4": 8,
                        },
                        psid: "68081e2a5d58a3ccf7c164fa",
                        st: 4,
                        nst: 4,
                        lw: null,
                        pmt: null,
                        pcwc: 0,
                        fb: null,
                        sid: "68081e2a5d58a3ccf7c164fa_9_14",
                        blb: 100834.16,
                        blab: 100834.16,
                        bl: 100834.16,
                        ssaw: 0,
                        wbn: null,
                        ocr: null,
                        mr: null,
                        smr: null,
                        rwsp: null,
                        hashr: "8:5;6;6#5;6;6#5;6;6#MV#0.0#MT#1#MG#0.0#",
                        rl: [
                            5,
                            5,
                            5,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        aw: 0,
                        tw: 0,
                        orl: [
                            5,
                            5,
                            5,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        ctw: 0,
                        ml: 1,
                        wk: "0_C",
                        np: 0,
                        ge: [
                            2,
                            11,
                        ],
                        it: false,
                        imw: false,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        wp: null,
                        it: false,
                        isf: false,
                        cwc: 0,
                        fb: null,
                        sid: "68081e2a5d58a3ccf7c164fa_10_14",
                        wk: "0_C",
                        wfg: null,
                        gm: 1,
                        smr: null,
                        crtw: 0,
                        rcl: 0,
                        fstc: {
                            "4": 9,
                        },
                        pcwc: 0,
                        hashr: "9:4;6;6#4;6;6#4;6;6#MV#0.0#MT#1#MG#0.0#",
                        ocr: null,
                        ibs: false,
                        orl: [
                            4,
                            4,
                            4,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        ssaw: 0,
                        pmt: null,
                        cs: 0.08,
                        ge: [
                            2,
                            11,
                        ],
                        imw: false,
                        bns: null,
                        gwt: -1,
                        ml: 1,
                        psid: "68081e2a5d58a3ccf7c164fa",
                        wbn: null,
                        bl: 100834.16,
                        tb: 0,
                        rwsp: null,
                        pf: 1,
                        wt: "C",
                        tw: 0,
                        rl: [
                            4,
                            4,
                            4,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        ism: false,
                        ctw: 0,
                        wid: 0,
                        blab: 100834.16,
                        np: 0,
                        lw: null,
                        ab: null,
                        st: 4,
                        nst: 4,
                        aw: 0,
                        blb: 100834.16,
                        tbb: 0.4,
                        mr: null,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        wbn: null,
                        wfg: null,
                        ge: [
                            3,
                            11,
                        ],
                        lw: {
                            "1": 0.24,
                            "2": 0.24,
                            "3": 0.24,
                            "4": 0.24,
                            "5": 0.24,
                        },
                        orl: [
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        imw: false,
                        rcl: 0,
                        cwc: 0,
                        ab: null,
                        crtw: 0,
                        gm: 1,
                        smr: [
                            4,
                            6,
                            6,
                            6,
                            2,
                        ],
                        gwt: -1,
                        cs: 0.08,
                        pf: 1,
                        aw: 0,
                        wk: "0_C",
                        pmt: null,
                        st: 4,
                        blb: 100834.16,
                        np: 0,
                        it: false,
                        ssaw: 0,
                        fstc: {
                            "4": 10,
                        },
                        pcwc: 0,
                        wid: 0,
                        wt: "C",
                        blab: 100834.16,
                        tb: 0,
                        ctw: 1.2,
                        sid: "68081e2a5d58a3ccf7c164fa_11_14",
                        nst: 3,
                        bns: null,
                        ism: true,
                        mr: null,
                        hashr: "10:6;6;6#6;6;6#6;6;6#R#6#011121#MV#0.0#MT#1#R#6#001020#MV#0.0#MT#1#R#6#021222#MV#0.0#MT#1#R#6#001122#MV#0.0#MT#1#R#6#021120#MV#0.0#MT#1#MG#0.0#",
                        fb: null,
                        rl: [
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        psid: "68081e2a5d58a3ccf7c164fa",
                        bl: 100834.16,
                        tbb: 0.4,
                        tw: 0,
                        ocr: null,
                        ml: 1,
                        wp: {
                            "1": [
                                1,
                                4,
                                7,
                            ],
                            "2": [
                                0,
                                3,
                                6,
                            ],
                            "3": [
                                2,
                                5,
                                8,
                            ],
                            "4": [
                                0,
                                4,
                                8,
                            ],
                            "5": [
                                2,
                                4,
                                6,
                            ],
                        },
                        isf: false,
                        ibs: true,
                        rwsp: {
                            "1": 3,
                            "2": 3,
                            "3": 3,
                            "4": 3,
                            "5": 3,
                        },
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        pmt: null,
                        cs: 0.08,
                        wid: 0,
                        blb: 100834.16,
                        bl: 100834.16,
                        mr: null,
                        wp: null,
                        ssaw: 0,
                        isf: false,
                        fstc: {
                            "3": 1,
                            "4": 10,
                        },
                        ab: null,
                        wk: "0_C",
                        wbn: null,
                        tw: 0,
                        crtw: 0,
                        gwt: -1,
                        psid: "68081e2a5d58a3ccf7c164fa",
                        st: 3,
                        blab: 100834.16,
                        ibs: true,
                        ism: false,
                        rcl: -1,
                        bns: {
                            mrl: [
                                0,
                                0,
                                2,
                                0,
                                0,
                                0,
                                0,
                                0,
                                0,
                            ],
                            ltw: 1.2,
                            lws: 6,
                            nmp: 2,
                        },
                        sid: "68081e2a5d58a3ccf7c164fa_12_14",
                        nst: 3,
                        wfg: null,
                        ge: [
                            3,
                            11,
                        ],
                        imw: false,
                        pcwc: 0,
                        hashr: "11:-1;-1;-1#-1;-1;-1#-1;-1;-1#MV#0.0#MT#2#MG#0.0#",
                        pf: 1,
                        wt: "C",
                        tbb: 0.4,
                        ocr: null,
                        orl: [
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                        ],
                        fb: null,
                        rl: [
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                        ],
                        aw: 0,
                        np: 0,
                        ml: 1,
                        lw: null,
                        gm: 2,
                        it: false,
                        smr: null,
                        cwc: 0,
                        rwsp: null,
                        tb: 0,
                        ctw: 0,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        st: 3,
                        blb: 100834.16,
                        ocr: null,
                        orl: [
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                        ],
                        smr: null,
                        cwc: 0,
                        bl: 100834.16,
                        np: 0,
                        rwsp: null,
                        psid: "68081e2a5d58a3ccf7c164fa",
                        isf: false,
                        ibs: true,
                        rcl: -1,
                        fstc: {
                            "3": 2,
                            "4": 10,
                        },
                        nst: 3,
                        wid: 0,
                        mr: null,
                        ge: [
                            3,
                            11,
                        ],
                        sid: "68081e2a5d58a3ccf7c164fa_13_14",
                        crtw: 0,
                        gwt: -1,
                        ctw: 0,
                        cs: 0.08,
                        pf: 1,
                        lw: null,
                        hashr: "12:-1;-1;-1#-1;-1;-1#-1;-1;-1#MV#0.0#MT#4#MG#0.0#",
                        rl: [
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                            -1,
                        ],
                        wt: "C",
                        wbn: null,
                        wfg: null,
                        blab: 100834.16,
                        tbb: 0.4,
                        it: false,
                        ssaw: 0,
                        imw: false,
                        pcwc: 0,
                        aw: 0,
                        wk: "0_C",
                        tw: 0,
                        gm: 4,
                        bns: {
                            mrl: [
                                0,
                                0,
                                2,
                                0,
                                0,
                                0,
                                0,
                                0,
                                2,
                            ],
                            ltw: 1.2,
                            lws: 6,
                            nmp: 8,
                        },
                        pmt: null,
                        fb: null,
                        ab: null,
                        ml: 1,
                        tb: 0,
                        wp: null,
                        ism: false,
                    },
                },
                err: null,
            },
            {
                dt: {
                    si: {
                        crtw: 0,
                        bns: {
                            mrl: [
                                0,
                                0,
                                2,
                                0,
                                0,
                                0,
                                0,
                                0,
                                2,
                            ],
                            ltw: 1.2,
                            lws: 6,
                            nmp: -1,
                        },
                        pcwc: 0,
                        it: false,
                        isf: false,
                        orl: [
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        ssaw: 0,
                        cwc: 2.666667,
                        wid: 0,
                        tb: 0,
                        gm: 4,
                        np: 4.8,
                        ism: false,
                        rcl: -1,
                        nst: 1,
                        wk: "0_C",
                        smr: null,
                        imw: false,
                        pmt: null,
                        rwsp: null,
                        hashr: "13:6;6;6#6;6;6#6;6;6#MV#0.0#MT#4#MG#0.7#",
                        psid: "68081e2a5d58a3ccf7c164fa",
                        st: 3,
                        aw: 4.8,
                        wp: null,
                        gwt: 2,
                        fstc: {
                            "3": 3,
                            "4": 10,
                        },
                        pf: 1,
                        wt: "C",
                        wbn: null,
                        wfg: null,
                        blab: 100834.16,
                        ibs: true,
                        ctw: 4.8,
                        rl: [
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                            6,
                        ],
                        sid: "68081e2a5d58a3ccf7c164fa_14_14",
                        bl: 100838.96,
                        tbb: 0.4,
                        ocr: null,
                        fb: null,
                        ab: null,
                        cs: 0.08,
                        blb: 100834.16,
                        tw: 4.8,
                        mr: null,
                        ge: [
                            1,
                            11,
                        ],
                        ml: 1,
                        lw: null,
                    },
                },
                err: null,
            },
        ] as unknown as IncanWondersItem[]

        let sourceMap = new Map<string, string>()
        let results = []
        for (let i = 0; i < 7; i++) {
            let newData = Tool.deepClone(win_bet_9)
            let backItem = newData[newData.length - 1]
            backItem.dt.si.bns.mrl[1] = 0
            backItem.dt.si.bns.mrl[2 + i] = 3

            backItem = newData[newData.length - 2]
            backItem.dt.si.bns.mrl[1] = 0
            backItem.dt.si.bns.mrl[2 + i] = 3

            results.push(newData)
        }

        for (let i = 0; i < 7; i++) {
            let newData = Tool.deepClone(win_bet_12)
            let backItem = newData[newData.length - 3]
            backItem.dt.si.bns.mrl[2] = 0

            let rndNum1 = Tool.randomInt(0, 4)
            let rndNum2 = Tool.randomInt(5, 8)
            backItem.dt.si.bns.mrl[rndNum1] = 2


            backItem = newData[newData.length - 2]
            backItem.dt.si.bns.mrl[2] = 0
            backItem.dt.si.bns.mrl[8] = 0
            backItem.dt.si.bns.mrl[rndNum1] = 2
            backItem.dt.si.bns.mrl[rndNum2] = 2

            backItem = newData[newData.length - 1]
            backItem.dt.si.bns.mrl[2] = 0
            backItem.dt.si.bns.mrl[8] = 0
            backItem.dt.si.bns.mrl[rndNum1] = 2
            backItem.dt.si.bns.mrl[rndNum2] = 2

            results.push(newData)
        }

        for (let i = 0; i < results.length; i++) {
            let newData = results[i]
            newData[0].dt.si.sid = "1765496350611716556" + i
            newData[0].dt.si.psid = "176549635061117654963506117165567736" + i
            newData[0].dt.si.hashr = "0:3;3;3#3;3;3#3;3;3#R#3#1256315441#MV#0.15#MT#1#R#3#001020#MV#0.15#MT#1#R#3#145415#MV#0.15#MT#1#R#3#001122#MV#0.15#MT#1#R#3#021120#MV#0.15#MT#1#MG#37.50#" + i


            let stringData = JSON.stringify(newData.map((o) => JSON.stringify(o)));
            let fileName = Tool.makeDeterministicName(stringData)
            if (sourceMap.get(fileName)) {

                continue
            }
            sourceMap.set(fileName, stringData)
        }

        console.log(results)

        console.log(`一共造出${sourceMap.size}条数据`)
        for (let [fileName, stringData] of sourceMap) {
            Tool.writeFile(`gen_data/gen_incanwonders_data/${fileName}`, stringData)
            //console.log(`gen file${fileName}`)
        }

    }
}

CreateSpinData.createIncanWonders()